ShoppingBasket/ShoppingBasket.Web/Models/ErrorViewModel.cs
using System;

namespace ShoppingBasket.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShoppingBasket/ShoppingBasket.Web/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingBasket.Web.Models
{
    public class Order
    {
        public int Milk { get; set; }
        public int Butter { get; set; }
        public int Bread { get; set; }
        public decimal? Total { get; set; }
    }
}

ShoppingBasket/ShoppingBasket.Web/Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingBasket.Web.Models;
using ShoppingBasket.Web.Services;

namespace ShoppingBasket.Web.Controllers
{
    public class BasketController : Controller
    {
        private readonly ProductRepository _productRepository;
        private readonly BasketFactory _basketFactory;
        
        public BasketController(ProductRepository productRepository, BasketFactory basketFactory)
        {
            _productRepository = productRepository;
            _basketFactory = basketFactory;
        }

        public IActionResult Index()
        {
            return View(new Order{});
        }

        public IActionResult Calculate(Order order)
        {
            var basket = _basketFactory.CreateBasket();
            basket.AddProduct(_productRepository.GetByName("Milk"), order.Milk);
            basket.AddProduct(_productRepository.GetByName("Butter"), order.Butter);
            basket.AddProduct(_productRepository.GetByName("Bread"), order.Bread);
            order.Total = basket.Total;
            return View("index",order);
        }
    }
}

ShoppingBasket/ShoppingBasket.Web/Views/Basket/Index.cshtml
@using System.Xml.Schema
@model Order
@{
    ViewData["Title"] = "ShoppingBasket";    
}
<div>
    <form action="@Url.Action("Calculate")" method="post">
        <table>
            <tr><td>Butter</td><td>£0.80 </td><td>@Html.TextBoxFor(i => i.Butter, new { @type = "number", min="0"}) </td></tr>
            <tr><td>Milk</td><td>£1.15 </td><td>@Html.TextBoxFor(i => i.Milk, new { @type = "number", min = "0" }) </td></tr>
            <tr><td>Bread</td><td>£1.00 </td><td>@Html.TextBoxFor(i => i.Bread, new { @type = "number", min = "0" }) </td></tr>
        </table>
        <input type="submit" />
    </form>

    @if (Model.Total.HasValue)
    {
        <div> Total is @Model.Total</div>
    }
    
</div>

ShoppingBasket/ShoppingBasket.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingBasket.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Basket" asp-action="Index" class="navbar-brand">ShoppingBasket.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Basket" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ShoppingBasket.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>